### PR TITLE
Release v2.0.0

### LINKED ISSUE #13: what is acutally needed for pc:schemas
Hi, I am trying to utilize the point Cloud extension but am running into issues with the required schemas. 

I used the pdal to STAC .py(https://github.com/stac-extensions/pointcloud/blob/main/examples/pdal-to-stac.py) script to create a JSON, the call to apply the schema to the point cloud extension returns the error: dict object has not attribute to_dict

the portion of the json schema looks like this:
```
 "pc:schemas": [
      {
        "name": "X",
        "size": 8,
        "type": "floating"
      },
      {
        "name": "Y",
        "size": 8,
        "type": "floating"
      },
      {
        "name": "Z",
        "size": 8,
        "type": "floating"
      },
      {
        "name": "Intensity",
        "size": 2,
        "type": "unsigned"
      }] 
```

**The full json can be found here: https://github.com/ElocF/BC_Webmap_Lidar_STAC/blob/main/src/bc_092o018_3_2_4_xyes_12_utm10_2018.json**

The call to assign the json section of the schema looks like this:

```
 for id, laz_info in laz_dict.items():
    for key in laz_info:
        # print(id)
        # print(key)
        # print(laz_info[key])
        laz_uri=key
        print(f"Processing {laz_uri}")
        #read json for corresponding laz file from s3
        laz_json=s3_client.get_object(Bucket=test_bucket, Key=laz_info[key])
        json_text = laz_json["Body"].read().decode()
        json_content= json.loads(json_text)

        # Extract bbox coordinates
        bbox_coords = json_content['bbox']
        left, bottom, right, top = bbox_coords[0], bbox_coords[1], bbox_coords[3], bbox_coords[4]   
        # Create bounding box
        bbox = [left, bottom, right, top]
        footprint = Polygon([(left, bottom), (right, bottom), (right, top), (left, top), (left, bottom)])
        footprint=mapping(footprint)
        
        point_count=(json_content['properties']['pc:count'])
        point_density=(json_content['properties']["pc:density"])
        point_schemas=(json_content['properties']["pc:schemas"])   # need to fix schema some how https://pystac.readthedocs.io/en/latest/api/extensions/pointcloud.html#pystac.extensions.pointcloud.Schema
        point_type=(json_content['properties']["pc:type"])
        point_stats=(json_content['properties']["pc:statistics"])
        point_epsg=(json_content['properties']["pc:epsg"])
        
        print(point_schemas)
        
        item=pystac.Item(
            id=f"laz{id}", 
            geometry=footprint,
            bbox=bbox,
            datetime=datetime.utcnow(),
            properties={},
        )
        item.validate
        
        #look to see if any of the common_metadata would be good for us
        # maybe license?
        #https://pystac.readthedocs.io/en/latest/api/common_metadata.html
        # item.common_metadata.gsd = 0.3
        # item.common_metadata.platform = "Maxar"
        # item.common_metadata.instruments = ["WorldView3"]
        item.common_metadata.object=key 
        
        
        #set point cloud extension
        pc_ext = PointcloudExtension.ext(item,  add_if_missing=True).apply(
            count= point_count,
            type= point_type,
            encoding= "binary",                                   # not sure what to put for this??????
            schemas= point_schemas,
            density= point_density,
            statistics=point_stats #,
            #epsg= point_epsg
        ) 
```
        
**The full script we are working on is located here: https://github.com/ElocF/BC_Webmap_Lidar_STAC/blob/main/src/STAC/Create_STAC.ipynb**

**what am I missing in regards to the schema??**

Thanks

### PR DESCRIPTION
**Pull request by gadomski**
The main changes are

- relaxing a required field to non-required (`pc:schemas`)
- removing a field (`pc:encoding`)

## Related issues

- Closes #13

### CODE REVIEW

**Comment by m-mohr** [comment]
> because [...] it is allowed to have fields w/ a pc: prefix that aren't in the extension.

That is not correct. Unknown pc: prefixed fields will be reported as invalid. @gadomski

**Comment by gadomski** [comment]
Alrighty, then should be v2.0.0. Thanks @m-mohr I'll update.

**Comment by m-mohr** [comment]
Generally, the schema could be updated to a better version that we use in some other extensions. I'm not sure it's in the template extension yet, but if you go 2.0.0 preferrably also improve the schema ;-)

**Comment by gadomski** [comment]
> Generally, the schema could be updated to a better version that we use in some other extensions. I'm not sure it's in the template extension yet, but if you go 2.0.0 preferrably also improve the schema ;-)

Ok, I'll hold off on merging and see if I can get some time to update the schema 👍🏼

**Comment by m-mohr** [comment]
Here's a recent example of a "better" schema ;-)
https://github.com/stac-extensions/eo/blob/9dfcf270dbd210e74ee1e06a15c50beedc2e3b5d/json-schema/schema.json

**Comment by gadomski** [comment]
@m-mohr I did my best to ape the EO extension into the jsonschema, but full disclosure I don't play in jsonschema much so mistakes are quite possible. If you have time to take a look I'd appreciate 🙇🏼 .

**Comment by m-mohr** [comment]
The CI tests fail, could you fix those first? :-)
Or any specific issues I should look at?

**Comment by gadomski** [comment]
> The CI tests fail, could you fix those first? :-)

Yeah, I'm flailing around now — please ignore, I'll ping again when I get things green 🙇🏼 .

**Review by ElocF — APPROVED** [review]

**Comment by gadomski** [comment]
@m-mohr did my best to update the schema using the "better" version, so ready for re-review (finally).

**Comment by m-mohr** [comment]
Oops! In the meantime I created an even better version 😅 (sorry!)
https://github.com/stac-extensions/eo/blob/main/json-schema/schema.json
or 
https://github.com/stac-extensions/raster/blob/main/json-schema/schema.json
I still need to generalize it for the template repository though.

It uses if/else instead of oneOf which makes the error reporting in JSON Schema less confusing to read and actually correctly validates fields "everywhere". Before it sometimes happened that parts were not validated.

**Comment by gadomski** [comment]
@m-mohr ok I've updated with The New Way, and added some more tests (for assets and item assets, respectively).

**Review by m-mohr — APPROVED** [review]
Should the count in pc:statistics have a minimum value of 0 or 1?

Otherwise LGTM.

**Comment by gadomski** [comment]
> Should the count in pc:statistics have a minimum value of 0 or 1?

It _could_ be a zero point file, that's allowed by most formats, so 0 seems right.

**Comment by m-mohr** [comment]
@gadomski Yes, but there was NONE defined. I'm not talking about pc:count, but about pc:statistics.count!

**Comment by gadomski** [comment]
Whoops. I'll open an issue, thanks!

**Pull request merged**
